<?php
return [
	'👧'                    => \App\Commands\Sex::class,
	'👦'                    => \App\Commands\Sex::class,
	'15'                    => \App\Commands\Age::class,
	'16..17'                => \App\Commands\Age::class,
	'18..20'                => \App\Commands\Age::class,
	'21..25'                => \App\Commands\Age::class,
	'26..'                  => \App\Commands\Age::class,
	'змінити область'       => \App\Commands\District::class,
	'✖️ скасувати'           => \App\Commands\Cancel::class,
	'⚙ налаштування'        => \App\Commands\Settings::class,
	'⬅️ назад'               => \App\Commands\MainMenu::class,
	'✉️ зворотній зв\'язок'  => \App\Commands\Feedback::class,
	'👁 мої пропозиції'      => \App\Commands\QuestionList::class,
	'➕ додати пропозицію'   => \App\Commands\AddQuestion\SetText::class,
	'всім 👫'                => \App\Commands\AddQuestion\SetSex::class,
	'👦🏼'                   => \App\Commands\AddQuestion\SetSex::class,
	'👧🏼'                   => \App\Commands\AddQuestion\SetSex::class,
	'всім 👶👵🏽'            => \App\Commands\AddQuestion\SetAge::class,
	'✅ так'                => \App\Commands\AddQuestion\ShowProfile::class,
	'✖️ ні'                 => \App\Commands\AddQuestion\ShowProfile::class,
	'🔔 сповіщення'         => \App\Commands\GetUpdates::class,
	'📑 зі списку'         => \App\Commands\AddQuestion\SetDistrict::class,
	'🌎 показати всім'      => \App\Commands\AddQuestion\SetDistrict::class,
];
